### ISSUE TITLE
zlib inflate error during compilation

### ISSUE THREAD

**Issue by LavergneV** [samtools/bcftools#1072]
Trying to compile bcftools-1.9 on a RedHat shared system (I am not sudo).

```
echo $LD_LIBRARY_PATH
/my_home/lib/gsl-2.5/lib:/my_home/lib/zlib-1.2.11/lib:/my_home/lib

cd bcftools-1.9
./configure --enable-libgsl CPPFLAGS="-I/my_home/lib/zlib-1.2.11"

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for grep that handles long lines and -e... /bin/grep
checking for C compiler warning flags... -Wall
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking location of HTSlib source tree... htslib-1.9
checking shared library type... plain .so
checking for library containing dlopen... -ldl
checking if the compiler accepts -rdynamic... yes
checking for zlib.h... yes
checking for inflate in -lz... no
configure: error: zlib development files not found

BCFtools uses compression routines from the zlib library <http://zlib.net>.
Building bcftools requires zlib development files to be installed on the build
machine; you may need to ensure a package such as zlib1g-dev (on Debian or
Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions) is installed.

FAILED.  This error must be resolved in order to build bcftools successfully.

```

Any idea ?
Thanks !

**Comment by jmarshall** [comment]
```
checking for zlib.h... yes
checking for inflate in -lz... no
```

Add `LDFLAGS="-L/my_home/lib/zlib-1.2.11/lib"` to your configure command. $LD_LIBRARY_PATH is effective only at runtime, not when compiling.

**Comment by jkbonfield** [comment]
This is an error while compiling the htslib component used by bcftools.  See the htslib INSTALL file for instructions on the third party libraries you need: https://github.com/samtools/htslib/blob/develop/INSTALL

It's easier if you can get your sysadmin to install them (the INSTALL notes list the package names), but otherwise you can install them locally and modify CPPFLAGS/LDFLAGS during ./configure.

**Comment by LavergneV** [comment]
@jmarshall 
Still the same error message after adding `LDFLAGS`

**Comment by jkbonfield** [comment]
Is /my_home/lib/zlib-1.2.11 an install tree or a source tree?  You'd be best to make a `/my_home/root` and compile and install all your third party libraries into that directory (eg with `./configure --prefix=/my_home/root; make; make install`.

Also note the INSTALL notes give hints how you can avoid LD_LIBRARY_PATH if you wish.  Eg via:

```
    ./configure CPPFLAGS=-I/usr/pkg/include \
                LDFLAGS='-L/usr/pkg/lib -Wl,-R/usr/pkg/lib'
```

**Comment by LavergneV** [comment]
@jkbonfield 
`/my_home/lib/` is the same as `$HOME/lib`

**Comment by valeriuo** [comment]
You may need the **zlib-devel** package to be installed, not only **zlib**.

Try `yum list installed | grep zlib-devel` and, if you don't get any results: 
`sudo yum install zlib-devel`

**Comment by LavergneV** [comment]
I reinstalled all dependencies listed in  https://github.com/samtools/htslib/blob/develop/INSTALL.

I am able to configure, but the make step triggers this error:
```
gcc -rdynamic -pthread -L/my_home/lib/zlib-1.2.11 -L/usr/lib64/ -L/my_home/lib/gsl-2.5 -L/my_home/lib/libbzip2 -L/my_home/lib/liblzma -L/my_home/lib/zlib-1.2.11 -L/usr/lib64/ -L/my_home/lib/gsl-2.5 -L/my_home/lib/libbzip2 -L/my_home/lib/liblzma -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o vcfplugin.o consensus.o ploidy.o bin.o hclust.o version.o regidx.o smpl_ilist.o csq.o vcfbuf.o mpileup.o bam2bcf.o bam2bcf_indel.o bam_sample.o vcfsort.o ccall.o em.o prob1.o kmin.o  polysomy.o peakfit.o htslib-1.9/libhts.a -lpthread -lz -lm -lbz2 -llzma -lm -lz -ldl -ldl  -lgsl -lgslcblas
peakfit.o: In function `peakfit_run':
/my_home/lib/bcftools-1.9/peakfit.c:556: undefined reference to `gsl_multifit_fdfsolver_test'
collect2: error: ld returned 1 exit status
make: *** [Makefile:138: bcftools] Error 1
```

**Comment by pd3** [comment]
This comes from GSL (`-lgsl`), what version of the library do you have? It was tested with GSL 1.5 and 2.4.

**Comment by jmarshall** [comment]
Conda have now updated their bcftools package to include GSL and `polysomy`, and it builds fine against their packaged GSL 2.5. So there's no compatibility problem with GSL-2.5. (And hence if you are a conda user you could now install it that way.)

Probably the problem is that `-L/my_home/lib/gsl-2.5` is not the location within your GSL build that contains _libgsl.so.23_, so you would need to adjust that path (or better use `make install` and point to the installed _…/lib_ path — see @jkbonfield's earlier https://github.com/samtools/bcftools/issues/1072#issuecomment-522923966).

But really you'd be best off talking to the administrators of your shared Red Hat system and getting them to install basic generic system development packages like **zlib-devel** and **gsl-devel**. This will be easier than doing it yourself.

**Comment by LavergneV** [comment]
It works with GSL 2.4 indeed.
Also works with conda.

Thanks guys !
