### ISSUE TITLE
fails to compile with gsl 2.1

### ISSUE THREAD

**Issue by wookietreiber** [samtools/bcftools#387]
```
$ make USE_GPL=1
gcc -g -Wall -Wc++-compat -O2 -I. -Ihtslib-1.3 -DPLUGINPATH=\"/usr/local/libexec/bcftools\" -DUSE_GPL  -c -o peakfit.o peakfit.c
peakfit.c: In function ‘peakfit_run’:
peakfit.c:553:41: error: ‘gsl_multifit_fdfsolver {aka struct <anonymous>}’ has no member named ‘J’
             gsl_multifit_gradient(solver->J, solver->f, grad);
                                         ^
Makefile:102: recipe for target 'peakfit.o' failed
make: *** [peakfit.o] Error 1
```

GSL:

```
$ gsl-config --version
2.1
```

**Comment by mcshane** [comment]
Should already be fixed on develop (duplicate of #378 and fixed by 681d80c20d078f953ff39140f7e519c94cb4fd1d). Please reopen if not.

**Comment by wookietreiber** [comment]
Thanks for the quick reply. Sorry about the duplicate.
